sudo: required

services:

    - docker

before_install:

    - docker pull ikelewis/cpp-coveralls

script:

    - docker run -it --rm -v ${PWD}/docker:/entrypoint/:ro -e UPLOAD_COVERAGE=yes --entrypoint=/entrypoint/coveralls.sh ikelewis/cpp-coveralls